#!/usr/bin/env bash
# This scrypt update the server and install nginx

sudo apt-get update -y
sudo apt-get install nginx -y
sudo rm -r /var/www/html/*
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
