#!/usr/bin/env bash
# This scrypt update the server and install haproxy                                                                                                                             
sudo apt-get install software-properties-common -y                                                                                                                               
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.0.\* -y

echo "
frontend my_frontend
        bind *:80
	mode http
        stats uri /haproxy?stats
        default_backend my_backend" >> /etc/haproxy/haproxy.cfg 

echo "
backend my_backend
        balance roundrobin
        server 885-web-01 34.73.4.188:80 check
        server 885-web-02 35.237.83.22:80 check" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
