#!/usr/bin/env bash
# script that displays a list of currently running processes
# using the command ps, and the optiones
# a - to show the tty
# u - display user-oriented format
# x - to print all proccess
# f - hierarchy
ps -auxf
