#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# and print in position 9 "hi"
i="0"
while [ $i -lt "10" ]; do
	if ((i == "8")); then
		echo "Holberton School"
		echo "hi"
	 else
		 echo "Holberton School"
	 fi
	 i=$((i + 1))
done
