#!/usr/bin/env bash
# This script is displaying "1" to "20" using while
# display in position 4 "bad luck from China"
# display in position 9 "bad luck from Japan"
# display in position 17 "bad luck from Italy"
i="0"
j="1"
while [ $i -le "12" ]; do
	echo "Hour: $i"
	while [ $j -lt "60" ]; do
		echo $j
		j=$((j + 1))
	done
	j="1"
	i=$((i + 1))
done
