#!/usr/bin/env bash
# Copy the file /etc/hosts in hosts.new
# Change the 127.0.0.1 for 127.0.0.2 - localhost
# Chamge the 8.8.8.8  for resolve facebook.com
# after copy the hosts.net to /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
