#!/usr/bin/env bash
# running service with nginx user
sudo chown nginx. /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default 
sudo pkill apache2
sudo -u nginx service nginx restart
